### ISSUE TITLE
bug: Error: Unable to resolve module @trigger.dev/core/v3 

### ISSUE THREAD

**Issue by maxckelly** [triggerdotdev/trigger.dev#1490]
### Provide environment information

"@trigger.dev/react-hooks": "^3.2.1",
React native

### Describe the bug

Hi - I'm trying to use the react hooks as stated in the documentation but whenever I try to call authentication or subscribe I get the below error. Can someone please help.

```
Error: Unable to resolve module @trigger.dev/core/v3 from /Users/USER/other/PROJECT/node_modules/@trigger.dev/react-hooks/dist/commonjs/hooks/useApiClient.js: @trigger.dev/core/v3 could not be found within the project or in these directories:
  node_modules
  3 | Object.defineProperty(exports, "__esModule", { value: true });
  4 | exports.useApiClient = useApiClient;
> 5 | const v3_1 = require("@trigger.dev/core/v3");
    |                       ^
  6 | const contexts_js_1 = require("../contexts.js");
  7 | /**
  8 |  * Hook to create an API client instance using authentication context or provided options.
    at ModuleResolver.resolveDependency (Users/USER/other/PROJECT/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:138:15)
    at DependencyGraph.resolveDependency (Users/USER/other/PROJECT/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Users/USER/other/PROJECT//node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (Users/USER/other/PROJECT/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (Users/USER/other/PROJECT/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at async Promise.all (index 1)
    at async visit (/Users/USER/other/PROJECT/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 17)
    at async visit (Users/USER/other/PROJECT/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 7)
```

### Reproduction repo

https://github.com/triggerdotdev/trigger.dev

### To reproduce

Build react native application and install package as stated in docs

**Comment by Cirr0e** [comment]
Hi there! I understand you're encountering a module resolution error while trying to use @trigger.dev/react-hooks in your React Native project.

The error you're seeing suggests there's a compatibility issue between the React Native environment and the @trigger.dev packages. Looking at the underlying issue, this is happening because @trigger.dev/react-hooks is trying to import from @trigger.dev/core/v3, but this dependency isn't being resolved correctly in the React Native environment.

Here's what I suggest to resolve this:

1. First, make sure you have all the necessary dependencies installed:
```bash
npm install @trigger.dev/react-hooks@3.2.1 @trigger.dev/core@3.2.1
```

2. Since you're using React Native, you'll need to add the core package explicitly to your dependencies in package.json:
```json
{
  "dependencies": {
    "@trigger.dev/react-hooks": "^3.2.1",
    "@trigger.dev/core": "^3.2.1"
  }
}
```

3. After updating your dependencies, clear your React Native bundler cache:
```bash
# For Metro bundler
npx react-native start --reset-cache
```

Important considerations:
- React Native has specific module resolution rules that can sometimes conflict with packages designed primarily for web React
- Make sure all your @trigger.dev packages are on the same version to avoid compatibility issues
- You might need to configure Metro bundler to properly resolve these packages

If you're still experiencing issues after trying these steps, please let me know:
1. What version of React Native you're using
2. Your metro.config.js configuration (if you have customized it)
3. Whether you're using Expo or bare React Native

The error appears to be a module resolution issue rather than a functional one, so once we get the packages properly resolved, you should be able to use the React hooks as documented.

Let me know if you need any clarification or run into other issues!

**Comment by thecoorum** [comment]
Hey @Cirr0e! I'm also experiencing the following issue using Expo SDK 52. I installed both `/react-hook` and `/core` packages, cleared the cache with `npx expo start --clear`, but it was still unsuccessful.

Here is the list of installed packages for me
```
"react": "18.3.1",
"react-dom": "18.3.1",
"react-native": "0.76.3",
"expo": "~52.0.11",
"@trigger.dev/core": "^3.3.5",
"@trigger.dev/react-hooks": "^3.3.5",
"@trigger.dev/sdk": "^3.3.5"
```

As I'm using the default Expo template it doesn't have `metro.config.js` generated (assuming it's not customized)

**Comment by rosswaycaster** [comment]
Hey @thecoorum and @maxckelly! Thanks to @Cirr0e for the initial troubleshooting help. I just solved this exact issue in my Expo SDK 52 project. I worked with [Claude (3.5 Sonnet)](https://anthropic.com/claude) through [Cursor's](https://cursor.com) agent functionality to find a solution, and I wanted to share what worked for us since we used this GitHub issue as context.

The key is that React Native's environment requires some additional configuration to resolve the Trigger.dev modules correctly. Here's what worked:

1. First, create a `metro.config.js` in your project root:

```javascript
const { getDefaultConfig } = require("expo/metro-config");

const config = getDefaultConfig(__dirname);

// Add additional module resolution rules
config.resolver.extraNodeModules = {
  "@trigger.dev/core/v3": require.resolve("@trigger.dev/core"),
};

// Ensure we handle all necessary file extensions
config.resolver.sourceExts = [...config.resolver.sourceExts, "mjs", "cjs"];

module.exports = config;
```

2. Create a provider component in `components/TriggerProvider.tsx`:

```typescript
"use client";

import { ReactNode } from "react";
import { TriggerAuthContext } from "@trigger.dev/react-hooks";

export function TriggerProvider({
  accessToken,
  baseURL,
  children,
}: {
  accessToken: string;
  baseURL?: string;
  children: ReactNode;
}) {
  return (
    <TriggerAuthContext.Provider
      value={{
        accessToken,
        baseURL,
      }}
    >
      {children}
    </TriggerAuthContext.Provider>
  );
}
```

3. Then you can use it in your components:

```typescript
import { Text, View, Pressable } from "react-native";
import { useRunTask } from "@trigger.dev/react-hooks";

export default function Index() {
  const { run, isLoading, error } = useRunTask({
    id: "hello-world",
    payload: { name: "World" },
  });

  return (
    <View className="flex-1 items-center justify-center">
      <Text className="text-2xl font-bold">Trigger.dev Test</Text>

      <Pressable onPress={() => run()} disabled={isLoading}>
        <Text>{isLoading ? "Running..." : "Run Hello World"}</Text>
      </Pressable>

      {error && <Text className="text-red-500">Error: {error.message}</Text>}
    </View>
  );
}
```

The key insight was that we just needed to help Metro resolve the modules correctly. After that, everything works as expected.

Hope this helps! Let me know if you need any clarification.

> This is Ross, I asked the Cursor agent to also write this comment :) Wild times!

**Comment by thecoorum** [comment]
@maxckelly I just understood that @Cirr0e is an automation bot for answers, so probably it won't always respond correctly. Did you resolve the issue for you by any chance?

**Comment by thecoorum** [comment]
@Cirr0e even with the suggested changes the bundling throws the following error
```
Unable to resolve "@trigger.dev/core/v3" from "node_modules/@trigger.dev/react-hooks/dist/commonjs/hooks/useApiClient.js"
```
and crashes the Expo Go app on project launch

**Comment by maxckelly** [comment]
Unfortunately haven't solved it yet. I've resorted to using my own backend and calling Trigger api to get results. Not ideal for now but best solution till i have more time to look at it

**Comment by Danfraga33** [comment]
Any solutions on this ?

**Comment by iamwillyj** [comment]
Same issue as @thecoorum Any updates?

**Comment by samejr** [comment]
Just wanted to be open about our general priorities regarding this issue.

At the moment we’re focusing on supporting web languages/frameworks so unfortunately mobile support is light and probably won’t be worked on for a while. We'd welcome community contributions if anyone wants to work on better React Native/Expo support.
